; mario state
FACING_RIGHT_BIT EQU 0


; Jump status
; 00 on ground;
; 01 ascending;
; 02 descending
MARIO_ON_GROUND EQU 0
MARIO_ASCENDING EQU 1
MARIO_DESCENDING EQU 2

MARIO_WALKING EQU 2
MARIO_RUNNING EQU 4

; block types
BLOCK_PIPE_OPENING EQU $70
BLOCK_BREAKABLE EQU $80
BLOCK_HIDDEN EQU $5F
BLOCK_COIN EQU $81
BLOCK_USED EQU $7F

POWERUP_MUSHROOM EQU $29
POWERUP_STAR EQU $34
POWERUP_ONE_UP EQU $2B
POWERUP_FLOWER EQU $2E

; hGameState
STATE_GAMEPLAY EQU 0
STATE_DEAD EQU 1
STATE_RESET_TO_CHECKPOINT EQU 2
STATE_PREPARE_DEATH EQU 3
STATE_DYING EQU 4
STATE_SCORE_COUNTING_DOWN EQU 5
STATE_LEVEL_END EQU 6
STATE_LEVEL_END_FX EQU 7
STATE_8 EQU 8
STATE_GOING_DOWN_PIPE EQU 9
STATE_WARP_TO_UNDERGROUND EQU 10
STATE_LEVEL_START EQU 11
STATE_12 EQU 12
STATE_AUTOSCROLL_LEVEL EQU 13
STATE_LOAD_MENU EQU 14
STATE_MENU EQU 15
STATE_16 EQU 16
STATE_START_LEVEL EQU 17
STATE_GOTO_BONUS_GAME EQU 18
STATE_ENTER_BONUS_GAME EQU 19
STATE_BONUS_GAME_SETUP_MARIO EQU 20
STATE_BONUS_GAME EQU 21
STATE_BONUS_MOVE_LADDER EQU 22
STATE_BONUS_WALKING EQU 23
STATE_BONUS_DESCEND_LADDER EQU 24
STATE_BONUS_ASCEND_LADDER EQU 25
STATE_BONUS_GETTING_PRICE EQU 26

STATE_PRE_GAMEOVER EQU 57
STATE_GAMEOVER EQU 58
STATE_PRE_TIMES_UP EQU 59
STATE_TIMES_UP EQU 59

SPRITE_HIDDEN  EQU $80
SPRITE_VISIBLE EQU $00

SPRITE_YFLIP EQU $40
SPRITE_XFLIP EQU $20

SPRITE_NO_FLIP EQU $00

